### ISSUE TITLE
Use of unresolved identifier "ConsoleAppender"

### ISSUE THREAD

**Issue by dwas** [jduquennoy/Log4swift#11]
I am using the following code from the examples. On the first line I am getting Use of unresolved identifier "ConsoleAppender"

```
let consoleAppender = ConsoleAppender("consoleAppender");
consoleAppender.formatter = defaultFormatter;
```

I am importing Log4swift on my AppDelegate. Am I missing something? Here is my full configureLogging method called from the onAppLoaded() method:

```
func configureLogging() {
    let sharedFactory = LoggerFactory.sharedInstance;

    let defaultFormatter = try! PatternFormatter(identifier: "default formatter", pattern: "%d - %m");

    let consoleAppender = ConsoleAppender("consoleAppender");
    consoleAppender.formatter = defaultFormatter;

    let fileAppender = FileAppender(identifier: "fileAppender", filePath: "/var/log/errors.log");
    fileAppender.formatter = defaultFormatter;
    fileAppender.thresholdLevel = .Error;

    sharedFactory.rootLogger.appenders = [consoleAppender, fileAppender];
    sharedFactory.rootLogger.thresholdLevel = .Info;

    let debugLogger = sharedFactory.getLogger("application.feature");
    debugLogger.thresholdLevel = .Debug;
}
```

**Comment by jduquennoy** [comment]
Hi Dwas,

I'm sorry my demo code was outdated : the ConsoleAppender has been renamed StdOutAppender some time ago. ConsoleAppender was misleading, as the logs it issues will not necessarily end up in the Console.app application : it uses stdOut (or stdErr, depending on the configuration and the log). So if you are running on Xcode, it will go to the IDE console, if you run in a terminal, it will print the logs in the terminal ...

Here is an updated configuration code : 

```
func configureLogging() {
    let sharedFactory = LoggerFactory.sharedInstance;

    let defaultFormatter = try! PatternFormatter(identifier: "default formatter", pattern: "%d - %m");

    let stdoutAppender = StdOutAppender("consoleAppender");
    stdoutAppender.formatter = defaultFormatter;

    let fileAppender = FileAppender(identifier: "fileAppender", filePath: "/var/log/errors.log");
    fileAppender.formatter = defaultFormatter;
    fileAppender.thresholdLevel = .Error;

    sharedFactory.rootLogger.appenders = [stdoutAppender, fileAppender];
    sharedFactory.rootLogger.thresholdLevel = .Info;

    let debugLogger = sharedFactory.getLogger("application.feature");
    debugLogger.thresholdLevel = .Debug;
}
```

You will also find easy configuration methods that you can call on LoggerFactory.sharedInstance :
- configureForXcodeConsole
- configureForSystemConsole
- configureForNSLogger

I know that the doc is not good enough today, and that the configuration is not easy enough. If you have some suggestion on how to make those two points better, I would love to hear your ideas !

Thanks for your message,

Jerome

**Comment by jduquennoy** [comment]
Hi Dwas,

Did that resolve your problem, can I close that issue ?

Jerome

**Comment by dwas** [comment]
Thanks for your help. You can close the issue.
