### ISSUE TITLE
Use of unresolved identifier 'NSString'

### ISSUE THREAD

**Issue by robertcerny** [jduquennoy/Log4swift#12]
Hello,
I spent last two days on this issue and still believe it must be something simple. I made a tvOS target and added all needed files into it and still getting bunch of errors while building the framework.
`Showing All Messages
/Users/rcerny/Developer/Projects/Net/Log4swift/Log4swift/Utilities/String+utilities.swift:25:56: Use of unresolved identifier 'NSString'

/Users/rcerny/Developer/Projects/Net/Log4swift/Log4swift/Utilities/String+utilities.swift:42:7: Use of unresolved identifier 'NSString'

/Users/rcerny/Developer/Projects/Net/Log4swift/Log4swift/Utilities/String+utilities.swift:88:22: Use of undeclared type 'NSString'

/Users/rcerny/Developer/Projects/Net/Log4swift/Log4swift/Utilities/String+utilities.swift:92:16: Use of unresolved identifier 'JSONSerialization'

/Users/rcerny/Developer/Projects/Net/Log4swift/Log4swift/Utilities/String+utilities.swift:92:66: Use of unresolved identifier 'JSONSerialization'`

Does anyone have any idea what could be wrong?

**Comment by Darkdah** [comment]
Hello Robert,

could be that there is just an

``` swift
import Foundation
```

statement missing in String+utilities.swift. I'll be able to check this tomorrow.

**Comment by robertcerny** [comment]
Nope, 
I still believe that it's something in the project settings because other targets build correctly

**Comment by jduquennoy** [comment]
Hi guys,

it is indeed a bit strange !
I'll look at that tomorrow, as soon as I have a minute.

Can you maybe attach the tvOS target that you created so that I can investigate ?
Are you building on XCode 7.3 or XCode 8 ?

Jerome

**Comment by robertcerny** [comment]
Hi,
I'm on Xcode 8.1 but tried version 8 as well. No difference.

**Comment by jduquennoy** [comment]
Hi Robert,

I pushed a commit that adds a target for tvOS.
It compiles fine here on Xcode 8.1.
Can you tell me if it works correctly for you too ?

Jerome

**Comment by robertcerny** [comment]
Well,
I'm going to investigate your settings because your target works great. Thanks!
