### ISSUE TITLE
Can't build for iOS with Carthage 

### ISSUE THREAD

**Issue by jhoughjr** [jduquennoy/Log4swift#16]
With Carthage 25 and 26 both Log4Swift does not build for me with 9A235. 
Simply states : 

*** Building scheme "log4swift-iOS" in Log4swift.xcodeproj
Failed to write to /Users/codemonkey/workspace/Poll-Pad-3/Carthage/Build/iOS/Log4swift.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “Log4swift.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/codemonkey/workspace/Poll-Pad-3/Carthage/Checkouts/Log4swift/build/ArchiveIntermediates/log4swift-iOS/BuildProductsPath/Release-iphoneos/Log4swift.framework, NSFilePath=/Users/codemonkey/workspace/Poll-Pad-3/Carthage/Checkouts/Log4swift/build/ArchiveIntermediates/log4swift-iOS/BuildProductsPath/Release-iphoneos/Log4swift.framework, NSUnderlyingError=0x7fc8aedfc000 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

Im in the "my project. won't build due to a million dependencies" situation. Never had issues with XCGLogger.

**Comment by jduquennoy** [comment]
H jhoughjr,

I'll prepare a carthage based project using Log4swift during the day to reproduce this issue.
Are you using Xcode 8 or Xcode 9 ?

**Comment by jduquennoy** [comment]
Hello again jhoughjr,
I was able to reproduce your problem, by changing the user configuration for the build results location.
It fails if Build Location is set to "legacy" in File -> Project Settings ... -> Advanced ...
It does not fail if I set it to Xcode Default, which will reuse the values of Xcode's preferences.

I have yet to find why this setting is reverted to "legacy" after every clone. This setting is stored in a user data file, that is not in the git repo (listed in .gitignore).

I'm still investigating, I suppose there is a setting in the project's configuration that will cause xcode to do that. Meanwhile, you can fix the setting on your side as a temporary workaround.

**Comment by jduquennoy** [comment]
One last message :-)
The day ends up here with some good news: The problem should be fixed, all tests (including the added test compiling with carthage) are green.
Can you confirm that the last commit works for you ?

**Comment by jduquennoy** [comment]
Hello,
After some days without notice, and. Onsidering that carthage based builds test are green, i’ll close this ticket.
Feel free to reopen it if you are still facing the problem.
Jerome
