### ISSUE TITLE
Build Issues while using pod

### ISSUE THREAD

**Issue by santhoshkumar-sn-7134** [jduquennoy/Log4swift#20]
Hi,
I am using your library in my project, I am facing the following issue as described below.
FYI 
`Platform: iOS`
`Compiler Version : Swift 4.1`

Screenshot of the issue
<img width="794" alt="screen shot 2018-07-10 at 5 49 19 pm" src="https://user-images.githubusercontent.com/41060300/42510411-6ce63ac4-846c-11e8-967c-7a29e220fc3a.png">

I can manually fix this issue by suggestion as shown below
<img width="1093" alt="screen shot 2018-07-10 at 5 57 07 pm" src="https://user-images.githubusercontent.com/41060300/42510450-8e0e05b0-846c-11e8-9c77-7a284215f200.png">

But if used above suggestion the following screen pops over
<img width="976" alt="screen shot 2018-07-10 at 5 57 24 pm" src="https://user-images.githubusercontent.com/41060300/42510494-b4cde03a-846c-11e8-8c7e-ed277599e406.png">

If I gave unlock permission the issue is fixed. For all issues same steps as has to be followed

I am using pod method to install this library, So I will not keep my pod libraries in my source.
Single pod file with dependency list will be available in source, So that pod libraries can be retrieved using `pod install` command.
 
If am sharing the code with developers in my team.
The developer have to repeat those steps specified above to fix the issue every time while installing pod libraries.

If the issue is resolved in your build, It will be helpful to developer community.

Regards,
Santhosh

**Comment by jduquennoy** [comment]
Hi Santhosh,
Indeed, I did not update for recent versions of swift yet.
Sorry for the inconvenience, I'll work on that today, to be compatible with swift 4.1, and if possible with 4.2 (to be released with Xcode 10 soon).
Thanks for your feedback !

**Comment by jduquennoy** [comment]
Hi again Santhosh,
Can you give branch swift4-xcode9 a test ?
The pod specification for that would be:
```
pod 'Log4swift', :git => 'https://github.com/jduquennoy/Log4swift.git', :branch => 'swift4-xcode9'
```
I tested on my side on Xcode 9 (swift 4.1) and Xcode 10 (swift 4.2) successfully.
If you can confirme that it works for you, I'll merge that branch to master, and push a new version of the pod.

**Comment by santhoshkumar-sn-7134** [comment]
Hi @jduquennoy,

I tested the branch, it builds successfully. Thanks for your quick response.

PS
Does your library has file rolling feature like Max noOfLogFiles,  sizeLimit per log file, rollingFrequency rolling file after particular time period.

Regards, 
Santhosh

**Comment by jduquennoy** [comment]
Perfect, I'll prepare a new version of the pod then.
Hopefully it will be online tomorrow.

About the rolling log files, it is not available as of now, but it would not be very complex to add to the fileAppender. I'll try to work on that as soon as possible (sorry, it is hard for me to give an ETA right now).
