### ISSUE TITLE
error: include of non-modular header inside framework module 'Log4swift.log4swift'

### ISSUE THREAD

**Issue by liorshalev01** [jduquennoy/Log4swift#4]
<module-includes>:1:9: note: in file included from <module-includes>:1:
# import "/Users/liorshalev01/heylo/heylo-ios/Pods/Target Support Files/Log4swift/Log4swift-umbrella.h"

```
    ^
```

/Users/liorshalev01/heylo/heylo-ios/Pods/Target Support Files/Log4swift/Log4swift-umbrella.h:3:9: note: in file included from /Users/liorshalev01/heylo/heylo-ios/Pods/Target Support Files/Log4swift/Log4swift-umbrella.h:3:
# import "log4swift.h"

```
    ^
```

/Users/liorshalev01/heylo/heylo-ios/Pods/Log4swift/Log4swift/log4swift.h:30:9: error: include of non-modular header inside framework module 'Log4swift.log4swift'
# import <Log4swift/NSLogger.h>

```
    ^
```

<module-includes>:1:9: note: in file included from <module-includes>:1:
# import "/Users/liorshalev01/heylo/heylo-ios/Pods/Target Support Files/Log4swift/Log4swift-umbrella.h"

```
    ^
```

/Users/liorshalev01/heylo/heylo-ios/Pods/Target Support Files/Log4swift/Log4swift-umbrella.h:3:9: note: in file included from /Users/liorshalev01/heylo/heylo-ios/Pods/Target Support Files/Log4swift/Log4swift-umbrella.h:3:
# import "log4swift.h"

```
    ^
```

/Users/liorshalev01/heylo/heylo-ios/Pods/Log4swift/Log4swift/log4swift.h:31:9: error: include of non-modular header inside framework module 'Log4swift.log4swift'
# import <Log4swift/LoggerClient.h>

```
    ^
```

Hi,

Xcode 7.1

Podfile:
use_frameworks!
target 'Heylo' do
  pod 'Log4swift', '1.0.0b4'
  pod 'AWSCore', '~> 2.3'
  pod 'AWSCognito', '~> 2.3'
  pod 'Fabric', '~> 1.6'
  pod 'TwitterCore', '~> 1.14'
  pod 'TwitterKit', '~> 1.14'
  pod 'PromiseKit', '~> 3.0'
  pod 'AFNetworking', '3.0.0-beta.3'
end

<module-includes>:1:9: note: in file included from <module-includes>:1:
# import "/Users/liorshalev01/heylo/heylo-ios/Pods/Target Support Files/Log4swift/Log4swift-umbrella.h"

```
    ^
```

/Users/liorshalev01/heylo/heylo-ios/Pods/Target Support Files/Log4swift/Log4swift-umbrella.h:3:9: note: in file included from /Users/liorshalev01/heylo/heylo-ios/Pods/Target Support Files/Log4swift/Log4swift-umbrella.h:3:
# import "log4swift.h"

```
    ^
```

/Users/liorshalev01/heylo/heylo-ios/Pods/Log4swift/Log4swift/log4swift.h:32:9: error: include of non-modular header inside framework module 'Log4swift.log4swift'
# import <Log4swift/LoggerCommon.h>

```
    ^
```

<module-includes>:1:9: note: in file included from <module-includes>:1:
# import "/Users/liorshalev01/heylo/heylo-ios/Pods/Target Support Files/Log4swift/Log4swift-umbrella.h"

```
    ^
```

/Users/liorshalev01/heylo/heylo-ios/Pods/Target Support Files/Log4swift/Log4swift-umbrella.h:3:9: note: in file included from /Users/liorshalev01/heylo/heylo-ios/Pods/Target Support Files/Log4swift/Log4swift-umbrella.h:3:
# import "log4swift.h"

```
    ^
```

/Users/liorshalev01/heylo/heylo-ios/Pods/Log4swift/Log4swift/log4swift.h:34:9: error: include of non-modular header inside framework module 'Log4swift.log4swift'
# import <Log4swift/ASLWrapper.h>

```
    ^
```

<unknown>:0: error: could not build Objective-C module 'Log4swift'

**Comment by jduquennoy** [comment]
Hi liorshalev01,
It looks like very similar to that issue Josete89 had a few months ago : https://github.com/jduquennoy/Log4swift/issues/3

The conclusion was that there was a problem with cocoapods, that was solved with Xcode 7.0, but back with Xcode 7.1.
Here is the bug at cocoaPod for this problem : https://github.com/CocoaPods/CocoaPods/issues/3767

Can you try to compile your project with Xcode 7.0 ? That could be useful to confirm the diagnostic.

Thanks,

Jérôme

**Comment by jduquennoy** [comment]
Hi again liorshalev01,
I have pushed a commit that might fix the problem of non modular header.
Can you give it a try, and tell me if it works better ?
You will need to specify the git repo in your podfile, as this version is not yet published :
`pod 'Log4swift', :git => 'https://github.com/jduquennoy/Log4swift.git'`

Thanks,

Jérôme

**Comment by jduquennoy** [comment]
Closing issue, as I have not more feedback.
Don't hesitate to re-open if needed !
