### ISSUE TITLE
Versioned File Appender

### ISSUE THREAD

**Issue by josealobato** [jduquennoy/Log4swift#9]
I Jerome, I have created a pull request with a patch of the file appender in which we avoid the log file to be overwritten every time the logger is launched. But with this patch the log file will grow forever. There is multiple solution to this small problem:
1. We check the size of the file and when it reach a value we add the date to the name of the log file and create a new one. We also only keep some of them. The number of files to keep and the size could be parameters one the appender configuration.
   Parameter could be:
   versionable: BOOL
   maxFileSize: 2Mb
   numberOfHistoryFiles: 10
2. We do the same as in 1 but create a new file on every run, keeping the las n ones with the creation date attached.
   Parameter could be:
   versionable: BOOL
   numberOfHistoryFiles: 10

What do you think?

**Comment by Darkdah** [comment]
I would vote for suggestion 1. But you should maybe also consider leaving the current file appender as is and implement your suggestion as a new appender: the rolling file appender.

If you improve the current file appender you should add an option in that allows the user to let the log file grow forever like it is now.

**Comment by josealobato** [comment]
That could work as well.
But in that case we need to inform in the documentation about the exact behaviour of the current one. That is that it gets overwritten every run.

**Comment by Darkdah** [comment]
Sorry for having been unclear with my thoughts, what I meant was that we could leave the the current file appender as is AFTER your pull request got accepted. The log file would grow forever, but it would be a feature. Those who don't want that feature could use the new rolling file appender.

**Comment by jduquennoy** [comment]
Hi Jose and Markus,

That would be great !
I agree with the proposal of a rolling file appender that would be override the file appender, to add the new behavior.
The ever-growing log file can be useful in environments where logs are rotated by an external service, like newsyslog (the one used on OS X) or logrotate. The FileAppender is built to work gracefully with such systems (it will re-create a log file on the fly if the previous one has been moved or deleted).

That is not very imaginative, but I would suggest to use the same behavior as Log4j's default one (at least in my memory) : once the file has reached the rolling condition, it is renamed by appending ".1" at the end. If a logFile.log.1 file exists, it is renamed to logFile.log.2.
I think we could also reuse their parameters names : _maxFileSize_ and _maxBackupIndex_.

For a later evolution, we could imagine having two kind of rolling conditions : one on the file size, with the numeric suffix added when rolling, and one with the date (hourly, daily, weekly, monthly, ...), that would add a meaningful suffix depending on the mode.
That would certainly be useful if swifts starts to get used on server side.

**Comment by josealobato** [comment]
Ok, Thanks. So I'll move to to do the implementation of the rolling file appender.

**Comment by santhoshkumar-sn-7134** [comment]
Hi, 
Is File rolling feature available,  If available how to use please can you help us with docs.

**Comment by jduquennoy** [comment]
Hi SanthoshSellavel,
I just pushed the rolling feature for the file appender. It is not yet integrated in the master branch, but you will find it on FileAppenderRotationFeature.
Can you take a look and tell me if it fits your expectations ? If you have a chance to give it a try, it would be awesome !
I did it so that custom rolling policies can be added, but for the moment, the naming of the rotated files is hard coded. I plan to add a naming policy protocol, with at least a simple implementation with '.1', '.2', '.3', so that rotated files name can also be customized if needed.
P.S.: the doc is not yet updated.

**Comment by santhoshkumar-sn-7134** [comment]
Hi @jduquennoy,

I have checked out file rolling feature, awesome work!
Everything works cool. By default SizeRotationPolicy can be used if maxFileSize is initialised.
Few suggestions,

- Instead getting filePath from user, If fileAppender dynamically create a logDirectory  and a Log file in that folder, adding set of properties to fileAppender like logFilePath or logDirectory to get those values will be more helpful. Or Add an option initialise fileAppender with logDirectory which makes more useful.

**Comment by jduquennoy** [comment]
As of today, the path of the file appender is configured with a destination file. The naming of the rotated log files is hard coded, a number is added to the filename, and the folder stays the same.

I was thinking about adding a new protocol, for an object that would be responsible for providing the rotated file name for a current file name.
The idea would be that when a rotation happens, this object is requested a new name for each file in the logging folder. It can then return a new name, or nil. If nil is returned, it means the provided file should not be renamed.
With such an object, a client of the library could specify its own naming policy.
It could, optionally, send the file to a subfolder by returning a relative path, or to a folder located elsewhere by returning an absolute path. But then log4swift will lost track of that file. This means that the file will no longer be rotated after it has been moved.
To avoid erasing files by mistake, Log4swift would still automatically add a suffix if the destination file already exists.

Do you think that would fit your needs ?

If yes, I think I will create the protocol, and two implementation: one equivalent to the currrent hard-codded one, that adds '.1', '.2, '.3' to the name of the file, and another one that would add the date at the end of the file name.

**Comment by ahmedAlmasri** [comment]
@jduquennoy  this Feature  in  `FileAppenderRotationFeature`, when to merge this with master ?

**Comment by jduquennoy** [comment]
Hi Ahmed,
The feature in that branch is validated, and covered by unit tests.
The issue I have is that I tried to add several test projects, to smoke test the library in different use cases (swift and obj-c, using carthage or cocoapods, on different platforms).
Some tests are running perfectly, but the ones using cocoaPods are failing. As I am not a user of cocoaPods, I need to spend time on it to fix the issue, but due to some recent changes in my live, it is not that easy to find spare time currently :-D.
I think I should merge the branch to master, but not release an official version before I can have all those tests working as expected.

Also the enhanced naming feature discussed in the previous post can probably come later.
